- url: 'https://soho.nascom.nasa.gov/data/realtime/hmi_igr/1024/latest.jpg'
  fileName: 'latest.jpg'
- url: 'https://soho.nascom.nasa.gov/data/realtime/c3/1024/latest.jpg'
  fileName: 'latest2.jpg'