- url: 'https://soho.nascom.nasa.gov/data/realtime/hmi_igr/1024/latest.jpg'
  fileName: 'latest.jpg'
- url: 'https://soho.nascom.nasa.gov/data/realtime/c3/1024/latest.jpg'
  fileName: 'latest2.jpg'
- url: 'https://soho.nascom.nasa.gov/data/realtime/eit_171/1024/latest.jpg'
  fileName: 'EIT171.jpg'
- url: 'https://soho.nascom.nasa.gov/data/realtime/c2/1024/latest.jpg'
  fileName: 'LASCO_C2.jpg'
- url: 'http://www.ncsm.city.nagoya.jp/astro/sun/now_wh.jpg'
  fileName: 'now_wh.jpg'
- url: 'http://www.ncsm.city.nagoya.jp/astro/sun/now_ha.jpg'
  fileName: 'now_ha.jpg'
- url: 'https://clouds.matteason.co.uk/images/8192x4096/clouds-alpha.png'
  fileName: 'clouds.jpg'
