name: 画像更新

on:
  schedule:
    - cron: '0 */3 * * *'  # 毎時0分に実行
  workflow_dispatch:      # 手動実行を可能にする

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
 
      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 依存関係のインストール
        run: |
          npm install js-yaml sharp

      - name: 画像の更新スクリプトを実行
        run: |
          node update_images.mjs

      - name: index.html を生成
        run: |
          TIMESTAMP=$(date '+%s')
          echo '<!DOCTYPE html>
          <html lang="ja">
          <head>
              <meta charset="UTF-8">
              <title>画像一覧</title>
          </head>
          <body>
              <h1>画像一覧</h1>
              <ul>
              　　　<p>SOHO</p>
                  <li><img src="latest.jpg?'$TIMESTAMP'" alt="latest.jpg"></li>
                  <li><img src="latest2.jpg?'$TIMESTAMP'" alt="latest2.jpg"></li>
                  <li><img src="EIT171.jpg?'$TIMESTAMP'" alt="EIT171.jpg"></li>
                  <li><img src="LASCO_C2.jpg?'$TIMESTAMP'" alt="LASCO_C2.jpg"></li>
                   <p>名古屋市科学館からの太陽像</p>
                  <li><img src="now_wh.jpg?'$TIMESTAMP'" alt="now_wh.jpg"></li>
                  <li><img src="now_ha.jpg?'$TIMESTAMP'" alt="now_ha.jpg"></li>
                   <p>live-cloud-maps</p>
                  <li><img src="clouds.jpg?'$TIMESTAMP'" alt="clouds.jpg"></li>
              </ul>
              <p>最終更新日時: '$(date '+%Y-%m-%d %H:%M:%S')'</p>
          </body>
          </html>' > _site/index.html

      - name: GitHub Pages 用のデータをアップロード
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: デプロイ
        uses: actions/deploy-pages@v4
