name: 画像更新

on:
  schedule:
    - cron: '0 * * * *'  # 毎時0分に実行
  workflow_dispatch:      # 手動実行を可能にする

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # リポジトリへの書き込み権限
      pages: write     # GitHub Pages への書き込み権限
      id-token: write  # デプロイに必要

    steps:
      - uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 依存関係のインストール
        run: |
          npm install js-yaml sharp

      - name: 画像の更新スクリプトを実行
        run: |
          node update_images.mjs

      - name: GitHub Pages 用のデータをアップロード
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site/

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write     # GitHub Pages への書き込み権限
      id-token: write  # デプロイに必要

    steps:
      - name: デプロイ
        uses: actions/deploy-pages@v1
