name: 画像更新

on:
  schedule:
    - cron: '0 * * * *'  # 毎時0分に実行
  workflow_dispatch:      # 手動実行を可能にする

jobs:
  update-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # リポジトリへの書き込み権限を付与

    steps:
      - uses: actions/checkout@v4  # バージョンを v4 に更新

      - name: 画像をダウンロード
        run: |
          mkdir -p image
          curl -L -o image/latest.jpg https://soho.nascom.nasa.gov/data/realtime/hmi_igr/1024/latest.jpg
          curl -L -o image/latest2.jpg https://soho.nascom.nasa.gov/data/realtime/c3/1024/latest.jpg

      - name: index.html を生成
        run: |
          TIMESTAMP=$(date '+%s')
          echo '<!DOCTYPE html>
          <html lang="ja">
          <head>
              <meta charset="UTF-8">
              <title>画像一覧</title>
          </head>
          <body>
              <h1>画像一覧</h1>
              <ul>
                  <li><a href="latest.jpg?'$TIMESTAMP'">latest.jpg</a></li>
                  <li><a href="latest2.jpg?'$TIMESTAMP'">latest2.jpg</a></li>
              </ul>
              <p>最終更新日時: '$(date '+%Y-%m-%d %H:%M:%S')'</p>
          </body>
          </html>' > image/index.html

      - name: 変更をコミットしてプッシュ
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add image/latest.jpg image/latest2.jpg image/index.html
          git commit --allow-empty -m "最新の画像を更新: $(date '+%Y-%m-%d %H:%M:%S')"
          git push
